import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Slider from "./components/slider";
import Provider from "./provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const getPoppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--poppins",
});
const getJosefinSans = Josefin_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--josef",
});
export const metadata = {
  title: "PsGaming",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} ${getPoppins.variable} ${getJosefinSans.variable} antialiased`}>
          <Provider>
            <div className="flex">
              <Slider />
              <div className='content absolute w-[calc(100%-310px)] min-h-screen right-0 py-8'>
                {children}
              </div>
            </div>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}