# Generated by Django 5.0 on 2025-02-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='background',
            field=models.FileField(default='backgrounds/default_background.jpg', upload_to='backgrounds/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.video')),
            ],
        ),
    ]
