# Generated by Django 5.0 on 2025-02-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='background',
            field=models.FileField(upload_to='backgrounds/'),
        ),
    ]
