# Generated by Django 5.0 on 2025-02-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_video_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
