# Generated by Django 5.0 on 2025-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='hello@gmail.com', max_length=254, null=True, unique=True),
        ),
    ]
